.eslintrc.json, client/src/App.js, client/src/App.test.js, client/src/index.js, client/src/registerServiceWorker.js, native-client/App.js, native-client/App.test.js, server/app.js, server/routes/index.js, server/routes/users.js
Added an eslintrc file, ran it on everything
=> Eslint add

README.md, client/package.json, native-client/App.js, native-client/package.json, package.json, server/app.js, server/views/error.jade, server/views/index.jade, server/views/layout.jade
This pull request will help set up our boilerplate code so we can move forward with a blank slate. Changes include:
-Removed the views folder and the code that required it in server/app.js
-Added 'speech-perfect' as project name in package.json files (sadly, I could not use train case as valid project name'
-Cleaned up App.js to be a basic starting point
=> chore: edited package.jsons and removed server views

.gitignore
This pull request would fix our .gitignore problem and finally untracks files we don't want added to Github.
=> Fix: no secrets

package.json, seed/userSeed.js
=> chore: made a user seed script

seed/userSeed.js
This pull request modifies our seed file to now include informative console.logs throughout the seeding process. It also features logins and passwords that are slightly easier to type, since the text box automatically capitalizes the first letter of input.
=> Refactor: modify seed file

native-client/assets/stylesheet.js, native-client/src/components/Recorder.js, native-client/src/components/Speeches.js, native-client/src/components/Timer.js, native-client/src/components/Uploader.js, native-client/src/screens/SingleReport.js
…sults and single report screens
=> feat: added styling to all of the pages, feat: uploaded backend to results pages

.gitignore, native-client/package.json, native-client/src/components/Login.js, native-client/src/components/Login.test.js, native-client/yarn.lock, server/package-lock.json
=> Login tests

native-client/src/components/Login.js, server/api/watson-api.js, server/db/models/index.js
This pull request merges code from Danny's work on the db and routes, Whit's on testing, and Micah's on the front end.
=> Feat: Audio post route adds to db

native-client/src/components/Recorder.js, native-client/src/components/Uploader.js, server/api/audio.js, server/api/watson-api.js
This pull request adds a functioning "send audio" button that creates new instances in our Sequelize models (with appropriate associations) and sends audio to both AWS and Watson.
=> Feat: Audio routes

package.json
Removed breaking comma in root package.json
=> Fix: package.json 

native-client/src/components/Recorder.js, native-client/src/components/Uploader.js, native-client/src/navigation/MainTabNavigator.js, native-client/src/screens/RecordScreen.js, native-client/src/screens/SingleReport.js, server/api/speech.js, server/api/watson-api.js
This pull request adds alerts when users submit recordings with no spoken words or bad confidence, and prevents them from being routed to AWS. It also redirects users to their results screen once the recording has ended.
=> Check confidence

native-client/src/components/SingleSpeechThumbnail.js, native-client/src/components/Speeches.js, native-client/src/screens/Profile.js, native-client/src/screens/SingleReport.js, server/api/speech.js
This pull request edits our delete routes so that they no longer require two passed parameters.
=> Refactor: delete routes

native-client/src/components/ReplayAudio.js, native-client/src/components/SpeechList.js, native-client/src/navigation/MainTabNavigator.js, native-client/src/screens/LoginScreen.js, native-client/src/screens/SignupScreen.js, native-client/src/screens/SingleReport.js, native-client/src/screens/WordRepetition.js, server/auth/index.js, server/db/models/user.js, server/seed/seed.js
This PR adds some safeguards on the authorization routes. Still needs more. Also, fixes navigation between pages in the Profile stack.
=> Auth fixes merge

native-client/src/components/ReplayAudio.js, native-client/src/components/Uploader.js, native-client/src/screens/SingleReportScreen.js, server/db/models/user.js
This pull request fixes bugs in transitioning between recording and reporting screen.
=> Feat: Audio fixes

native-client/src/components/Recorder.js, native-client/src/components/RecorderRender.js, native-client/yarn.lock, server/package-lock.json
The Recorder component had a very large rendering function. I've broken it up into many smaller functional pieces. Everything appears to be working correctly, but please test that it can actually still record sound before merging.
=> Recorder refactor

native-client/assets/stylesheet.js, native-client/src/components/Recorder.js
This PR fixes a bug in rendering Recorder.
=> fix: fixed render issue in recorder

server/api/audio.js
This pull request modifies our AWS server route to use env variables instead of imports from other files.
=> Fix: changed aws creds to env vars

native-client/src/screens/SingleReportScreen.js
"styles" isn't a real property, this was causing a crash
=> fix(SingleReportScreen): corrected styles property to style

package.json, server/api/speech.js, server/api/speech.spec.js, server/api/user.spec.js, server/db/models/user.js, server/package.json
This PR adds tests for our /api/user and /api/speech routes.
=> Feat: Tests

native-client/App.js, native-client/src/components/EditModal.js, native-client/src/components/EditTitleForm.js, native-client/src/components/Recorder.js, native-client/src/components/ReportData.js, native-client/src/components/Speeches.js, native-client/src/components/Uploader.js, native-client/src/screens/SignupScreen.js, server/api/audio.js, server/api/speech.js, server/api/speech.spec.js, server/api/watson-api.js, server/auth/auth.spec.js, server/auth/google.js, server/auth/index.js, server/db/models/user.spec.js, server/index.js
This PR adds tests for the auth routes on our backend, as well as incorporating code cleanup from a previous PR.
=> Feat: Auth tests
